package gui;

import dbUtil.GiaoVuDao;
import dbUtil.SinhVienDAO;
import pojo.GiaoVu;
import pojo.SinhVien;

import javax.swing.*;
import java.awt.*;

/**
 * gui
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 18-Jun-20 - 1:29 PM
 * @Description
 */
public class ChangePwGUI {
    private JPasswordField oldPWField;
    private JPasswordField newPWField;
    private JButton changeBtn;
    private JPanel changePWPanel;
    private JFrame frame;
    private final String username;
    private boolean type;

    public ChangePwGUI(String username, boolean type) {
        this.username = username;
        this.type = type;

        changeBtn.addActionListener(e -> {
            String oldPW = "";
            String newPW = "";

            if (this.oldPWField.getPassword().length > 0)
                oldPW = String.valueOf(this.oldPWField.getPassword());
            if (this.newPWField.getPassword().length > 0)
                newPW = String.valueOf(this.newPWField.getPassword());

            if (oldPW.isBlank() || newPW.isBlank())
                return;

            if (newPW.length() > 45) {
                JOptionPane.showMessageDialog(this.newPWField, "Mật khẩu mới quá dài!");
                return;
            }

            if (type) {
                GiaoVu gv = GiaoVuDao.get(this.username);

                if (!gv.getPassword().equals(oldPW)) {
                    JOptionPane.showMessageDialog(this.oldPWField, "Mật khẩu cũ không đúng!");
                    return;
                }
                gv.setPassword(newPW);

                if (!GiaoVuDao.update(gv)) {
                    JOptionPane.showMessageDialog(this.oldPWField, "Đổi mật khẩu thất bại!");
                    return;
                }
            } else {
                SinhVien sv = SinhVienDAO.get(this.username);

                if (!sv.getPassword().equals(oldPW)) {
                    JOptionPane.showMessageDialog(this.oldPWField, "Mật khẩu cũ không đúng!");
                    return;
                }
                sv.setPassword(newPW);

                if (!SinhVienDAO.update(sv)) {
                    JOptionPane.showMessageDialog(this.oldPWField, "Đổi mật khẩu thất bại!");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this.changePWPanel, "Đổi mật khẩu thành công!");
            this.frame.dispose();
        });
    }

    public void init() {
        frame = new JFrame("Login");
        frame.setContentPane(changePWPanel);
        frame.pack();
        frame.setResizable(false);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        changePWPanel = new JPanel();
        changePWPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Nhập mật khẩu cũ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        changePWPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changePWPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        changePWPanel.add(spacer2, gbc);
        oldPWField = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changePWPanel.add(oldPWField, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Nhập mật khẩu mới");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        changePWPanel.add(label2, gbc);
        newPWField = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changePWPanel.add(newPWField, gbc);
        changeBtn = new JButton();
        changeBtn.setText("Đổi mật khẩu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changePWPanel.add(changeBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return changePWPanel;
    }
}
