package gui;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;

import util.ImportCsv;

/**
 * gui
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 18-Jun-20 - 4:10 PM
 * @Description
 */
public class ImportCsvGUI {
    private JButton openBtn;
    private JPanel importPanel;
    private JButton closeBtn;
    private JFrame frame;
    private final int type;

    public ImportCsvGUI(int type) {
        this.type = type;

        openBtn.addActionListener(e -> {
            FileFilter filter = new FileNameExtensionFilter("CSV file", "csv");
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.setDialogTitle("Chọn file");
            jFileChooser.setFileFilter(filter);

            if (jFileChooser.showOpenDialog(importPanel) != JFileChooser.APPROVE_OPTION) {
                System.out.println("Error!");
                return;
            }

            File file = jFileChooser.getSelectedFile();

            boolean flag = false;
            if (this.type == 0)
                flag = ImportCsv.importSv(file);

            if (flag)
                JOptionPane.showMessageDialog(importPanel, "Import thành công!");
            else
                JOptionPane.showMessageDialog(importPanel, "Import thất bại!");
        });
        closeBtn.addActionListener(e -> {
            this.frame.dispose();
        });
    }

    public void init() {
        frame = new JFrame("Menu");
        frame.setContentPane(importPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        importPanel = new JPanel();
        importPanel.setLayout(new GridBagLayout());
        openBtn = new JButton();
        openBtn.setText("Chọn file");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        importPanel.add(openBtn, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        importPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        importPanel.add(spacer2, gbc);
        closeBtn = new JButton();
        closeBtn.setText("Đóng");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        importPanel.add(closeBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return importPanel;
    }
}
