package gui;

import gui.sv.ListSvGUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * PACKAGE_NAME
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 17-Jun-20 - 11:19 PM
 * @Description
 */
public class MenuGvGUI {
    private JPanel menuGv;
    private JButton newPWsBtn;
    private JButton logoutBtn;
    private JButton listSvBtn;
    private JButton importSvBtn;
    private JButton addSvBtn;
    private JButton updateSvBtn;
    private JButton removeSvBtn;
    private JButton listTkbBtn;
    private JButton importTkbBtn;
    private JButton listSvLopBtn;
    private JButton listSvLopHocBtn;
    private JButton importLopHocBtn;
    private JButton diemLopHocBtn;
    private JButton updateSvDiemBtn;
    private JButton importDiemBtn;
    private JFrame frame;
    private final String username;

    public MenuGvGUI(String username) {
        this.username = username;

        logoutBtn.addActionListener(e -> {
            frame.dispose();

            LoginGUI loginGUI = new LoginGUI();
            loginGUI.init();
        });
        newPWsBtn.addActionListener(e -> {
            ChangePwGUI cPW = new ChangePwGUI(this.username, true);
            cPW.init();
        });
        importSvBtn.addActionListener(e -> {
            ImportCsvGUI importCsvGUI = new ImportCsvGUI(0);
            importCsvGUI.init();
        });
        importTkbBtn.addActionListener(e -> {
            ImportCsvGUI importCsvGUI = new ImportCsvGUI(1);
            importCsvGUI.init();
        });
        importLopHocBtn.addActionListener(e -> {
            ImportCsvGUI importCsvGUI = new ImportCsvGUI(2);
            importCsvGUI.init();
        });
        importDiemBtn.addActionListener(e -> {
            ImportCsvGUI importCsvGUI = new ImportCsvGUI(3);
            importCsvGUI.init();
        });
        listSvBtn.addActionListener(e -> {
            ListSvGUI listSvGUI = new ListSvGUI();
            listSvGUI.init();
        });
    }

    public void init() {
        frame = new JFrame("Menu");
        frame.setContentPane(menuGv);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        menuGv = new JPanel();
        menuGv.setLayout(new GridBagLayout());
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        menuGv.add(tabbedPane1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Sinh Viên", panel1);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        listSvBtn = new JButton();
        listSvBtn.setText("Xem danh sách sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(listSvBtn, gbc);
        importSvBtn = new JButton();
        importSvBtn.setText("Import sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(importSvBtn, gbc);
        addSvBtn = new JButton();
        addSvBtn.setText("Thêm sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(addSvBtn, gbc);
        updateSvBtn = new JButton();
        updateSvBtn.setText("Sửa thông tin sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(updateSvBtn, gbc);
        removeSvBtn = new JButton();
        removeSvBtn.setText("Xóa sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(removeSvBtn, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Thời khóa biểu", panel2);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer4, gbc);
        listTkbBtn = new JButton();
        listTkbBtn.setText("Xem thời khóa biểu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(listTkbBtn, gbc);
        importTkbBtn = new JButton();
        importTkbBtn.setText("Import thời khóa biểu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(importTkbBtn, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Lớp", panel3);
        listSvLopBtn = new JButton();
        listSvLopBtn.setText("Xem danh sách lớp");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(listSvLopBtn, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer6, gbc);
        listSvLopHocBtn = new JButton();
        listSvLopHocBtn.setText("Xem danh sách lớp học");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(listSvLopHocBtn, gbc);
        importLopHocBtn = new JButton();
        importLopHocBtn.setText("Import lớp học");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(importLopHocBtn, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Điểm", panel4);
        diemLopHocBtn = new JButton();
        diemLopHocBtn.setText("Xem bảng điểm lớp");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(diemLopHocBtn, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel4.add(spacer8, gbc);
        updateSvDiemBtn = new JButton();
        updateSvDiemBtn.setText("Sửa điểm sinh viên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(updateSvDiemBtn, gbc);
        importDiemBtn = new JButton();
        importDiemBtn.setText("Import điểm");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(importDiemBtn, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Tài khoản", panel5);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel5.add(panel6, gbc);
        newPWsBtn = new JButton();
        newPWsBtn.setText("Đổi mật khẩu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(newPWsBtn, gbc);
        logoutBtn = new JButton();
        logoutBtn.setText("Đăng xuất");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(logoutBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menuGv;
    }

}
