package gui.lop;

import dbUtil.LopDAO;
import dbUtil.LopHocDAO;
import dbUtil.TkbDAO;
import gui.sv.ListSvGUI;
import pojo.Lop;
import pojo.LopHoc;
import pojo.Tkb;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * gui.lop
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 19-Jun-20 - 2:40 PM
 * @Description
 */
public class GetLopGUI {
    private JTextField maField;
    private JComboBox<String> maBox;
    private JButton openBtn;
    private JButton closeBtn;
    private JPanel getLopPanel;
    private JFrame frame;
    private final boolean type;
    private final List<String> list;

    public GetLopGUI(boolean type) {
        this.type = type;
        this.list = new ArrayList<>();

        closeBtn.addActionListener(e -> {
            this.frame.dispose();
        });
        maBox.addActionListener(e -> {
            if (Objects.requireNonNull(this.maBox.getSelectedItem()).toString() != null)
                this.maField.setText(this.maBox.getSelectedItem().toString());
        });
        openBtn.addActionListener(e -> {
            if (this.maField.getText() == null) {
                JOptionPane.showMessageDialog(this.maField, "Nhập mã lớp" + (type ? "!" : " học!"));
                return;
            }
            if (!this.list.contains(this.maField.getText())) {
                JOptionPane.showMessageDialog(this.maField, "Mã lớp" + (type ? "" : " học") + "không tồn tại!");
                return;
            }

            ListSvGUI listSvGUI = new ListSvGUI();
            listSvGUI.init((type ? 1 : 2), this.maField.getText());
        });
    }

    public void init() {
        this.createLopBox();

        if (this.list.isEmpty()) {
            JOptionPane.showMessageDialog(this.getLopPanel, "Danh sách rỗng!");
            return;
        }

        this.frame = new JFrame("Chọn lớp" + (type ? "" : " học"));
        this.frame.setContentPane(getLopPanel);
        this.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frame.pack();
        this.frame.setLocationRelativeTo(null);
        this.frame.setVisible(true);
    }

    void createLopBox() {
        if (this.type) {
            List<Lop> lopList = LopDAO.getList();
            for (Lop lop : lopList) {
                this.maBox.addItem(lop.getMaLop());
                this.list.add(lop.getMaLop());
            }
        } else {
            List<Tkb> tkbList = TkbDAO.getList();
            for (Tkb tkb : tkbList) {
                this.maBox.addItem(tkb.getMaTkb());
                this.list.add(tkb.getMaTkb());
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        getLopPanel = new JPanel();
        getLopPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Nhập mã");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        getLopPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getLopPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        getLopPanel.add(spacer2, gbc);
        maField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getLopPanel.add(maField, gbc);
        maBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getLopPanel.add(maBox, gbc);
        openBtn = new JButton();
        openBtn.setText("Xem");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getLopPanel.add(openBtn, gbc);
        closeBtn = new JButton();
        closeBtn.setText("Đóng");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getLopPanel.add(closeBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return getLopPanel;
    }
}
