package gui.tkb;

import dbUtil.TkbDAO;
import pojo.Tkb;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EventObject;
import java.util.List;

/**
 * gui.tkb
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 19-Jun-20 - 1:45 PM
 * @Description
 */
public class ListTkbGUI {
    private JPanel listTkbPanel;
    private JButton closeBtn;
    private JScrollPane scrollPanel;
    private JFrame frame;

    public ListTkbGUI() {
        closeBtn.addActionListener(e -> this.frame.dispose());
    }

    public void init() {
        if (!this.createTab()) {
            JOptionPane.showMessageDialog(this.listTkbPanel, "Thời khóa biểu rỗng!");
            return;
        }

        this.frame = new JFrame("Thời khóa biểu");
        this.frame.setContentPane(this.listTkbPanel);
        this.frame.add(this.scrollPanel);
        this.frame.pack();
        this.frame.setLocationRelativeTo(null);
        this.frame.setVisible(true);
    }

    boolean createTab() {
        List<Tkb> list = TkbDAO.getList();
        String[] colName = new String[]{
                "STT", "Mã môn", "Tên môn", "Phòng học", "Lớp"
        };
        String[][] colVal = new String[list.size()][5];
        for (int i = 0; i < list.size(); ++i) {
            colVal[i][0] = String.valueOf(i + 1);
            colVal[i][1] = list.get(i).getMaMon();
            colVal[i][2] = list.get(i).getMon().getTenMon();
            colVal[i][3] = list.get(i).getMon().getPhong();
            colVal[i][4] = list.get(i).getMaLop();
        }
        JTable tab = new JTable(colVal, colName) {
            public boolean editCellAt(int row, int column, EventObject e) {
                return false;
            }
        };
        tab.setRowSelectionAllowed(false);
        this.scrollPanel = new JScrollPane(tab);

        return !list.isEmpty();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        listTkbPanel = new JPanel();
        listTkbPanel.setLayout(new GridBagLayout());
        closeBtn = new JButton();
        closeBtn.setText("Đóng");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        listTkbPanel.add(closeBtn, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        listTkbPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        listTkbPanel.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return listTkbPanel;
    }
}
