package gui.sv;

import dbUtil.LopDAO;
import dbUtil.SinhVienDAO;
import pojo.Lop;
import pojo.SinhVien;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Objects;

/**
 * gui.sv
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 18-Jun-20 - 11:34 PM
 * @Description
 */
public class AddSvGUI {
    private JRadioButton mRadioBtn;
    private JRadioButton fRadioBtn;
    private JTextField cmndField;
    private JComboBox<String> lopBox;
    private JButton addBtn;
    private JButton closeBtn;
    private JTextArea mssvField;
    private JTextField nameField;
    private JPanel AddSvPanel;
    private JFrame frame;

    public AddSvGUI() {
        closeBtn.addActionListener(e -> {
            this.frame.dispose();
        });
        addBtn.addActionListener(e -> {
            if (this.mssvField.getText() == null || this.mssvField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this.mssvField, "Nhập MSSV!");
                return;
            }
            if (this.nameField.getText() == null || this.nameField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this.nameField, "Nhập họ và !");
                return;
            }
            if (this.cmndField.getText() == null || this.cmndField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this.cmndField, "Nhập CMND!");
                return;
            }
            if (!this.mRadioBtn.isSelected() && !this.fRadioBtn.isSelected()) {
                JOptionPane.showMessageDialog(this.mRadioBtn, "Chọn nam hoặc nữ!");
                return;
            }
            if (this.lopBox.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this.lopBox, "Chọn lớp!");
                return;
            }

            SinhVien sv = new SinhVien();
            sv.setMssv(this.mssvField.getText());
            sv.setHoTen(this.nameField.getText());
            sv.setGioiTinh(((this.mRadioBtn.isSelected()) ? "Nam" : "Nữ"));
            sv.setCmnd(this.cmndField.getText());
            sv.setMaLop(Objects.requireNonNull(this.lopBox.getSelectedItem()).toString());
            sv.setPassword(this.cmndField.getText());

            if (SinhVienDAO.add(sv)) {
                JOptionPane.showMessageDialog(this.AddSvPanel, "Thêm thành công!");
                return;
            }

            JOptionPane.showMessageDialog(this.AddSvPanel, "Thêm thất bại!");
        });
    }

    public void init() {
        this.createLopBox();

        this.frame = new JFrame("Thêm sinh viên");
        this.frame.setContentPane(AddSvPanel);
        this.frame.pack();
        this.frame.setLocationRelativeTo(null);
        this.frame.setVisible(true);
    }

    void createLopBox() {
        List<Lop> lopList = LopDAO.getList();
        for (Lop lop : lopList)
            this.lopBox.addItem(lop.getMaLop());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        AddSvPanel = new JPanel();
        AddSvPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("MSSV");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        AddSvPanel.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Họ và tên");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Giới tính");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(label3, gbc);
        mRadioBtn = new JRadioButton();
        mRadioBtn.setText("Nam");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(mRadioBtn, gbc);
        fRadioBtn = new JRadioButton();
        fRadioBtn.setText("Nữ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(fRadioBtn, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("CMND");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(label4, gbc);
        cmndField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(cmndField, gbc);
        lopBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(lopBox, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Lớp");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        AddSvPanel.add(label5, gbc);
        addBtn = new JButton();
        addBtn.setText("Thêm");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(addBtn, gbc);
        closeBtn = new JButton();
        closeBtn.setText("Đóng");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(closeBtn, gbc);
        mssvField = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        AddSvPanel.add(mssvField, gbc);
        nameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        AddSvPanel.add(nameField, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(mRadioBtn);
        buttonGroup.add(fRadioBtn);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return AddSvPanel;
    }
}
