package gui.sv;

import dbUtil.SinhVienDAO;
import pojo.SinhVien;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * gui
 *
 * @Created by pumpk - StudentID : 1712379
 * @Date 18-Jun-20 - 10:31 PM
 * @Description
 */
public class ListSvGUI {
    private JButton closeBtn;
    private JPanel listSvPanel;
    private JScrollPane scrollPanel;
    private JFrame frame;

    public ListSvGUI() {
        closeBtn.addActionListener(e -> frame.dispose());
    }

    public void init() {
        this.createTab();

        frame = new JFrame("Danh sách sinh viên");
        frame.setContentPane(listSvPanel);
        frame.add(scrollPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    void createTab() {
        List<SinhVien> list = SinhVienDAO.getList();
        String[] colName = new String[]{
                "STT", "MSSV", "Họ tên", "Giới tính", "CMND"
        };
        String[][] colVal = new String[list.size()][5];
        for (int i = 0; i < list.size(); ++i) {
            colVal[i][0] = String.valueOf(i + 1);
            colVal[i][1] = list.get(i).getMssv();
            colVal[i][2] = list.get(i).getHoTen();
            colVal[i][3] = list.get(i).getGioiTinh();
            colVal[i][4] = list.get(i).getCmnd();
        }
        JTable tab = new JTable(colVal, colName);
        scrollPanel = new JScrollPane(tab);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        listSvPanel = new JPanel();
        listSvPanel.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        listSvPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        listSvPanel.add(spacer2, gbc);
        closeBtn = new JButton();
        closeBtn.setText("Đóng");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        listSvPanel.add(closeBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return listSvPanel;
    }
}
